app:
  path:  # 获取语料的基准路径
    remote_base: \\192.168.1.8  # 远程服务器的路径
    base_path: \corpus\project\mddc  # 项目工程的基准路径
    cmd_path: /res/config.json  # 命令词配置文件相对工程的路径
    wav_path: train_mini  # 语料相对工程的路径
  controller:
    wav_count_one_cmder: 2  # 一条命令词的语料数量
    repeat_play_count: 1  # 一条语料的播放次数
    play_separator: 2  # 每次播放的时间间隔，单位: 秒
  log:
    log_filter:
      - agc handler
  interval: # 配置取值区间，用于识别计数，当无上限时，配置为 “x-max”; 当无下限时，配置为“min-x”（x表示数字）
    confidence:
      - 0-10
      - 10-max
    likelihood:
      - 0-10
      - 10-max
    svm:
      - 0-10
      - 10-max