app:
  remote:  # 配置用于语音检索，需要自行服务器上的 retrieve_wav.py 脚本
    host: 192.168.1.8
    port: 22
    username: root
    password:  root
  remote_base: \\192.168.1.8  # 远程服务器的路径，本地请配置卷标
  cmd_path: \corpus\project\mddc\res\config.json  # 命令词路径
  wav:
    load_mode: 1  # 1表示输入语料目录， 2表示输入wav.scp和text的目录
    wav_path: \corpus\train\wavs  # 语料库路径
    wav_schema:  # 读取以什么开头的语音
      - A
    retrieve_script: python3 /corpus/common/script-new/retrieve_wav.py {0} {1} {2}  # 检索语音的植入脚本， 参数：0:wav_path; 1:wav_schema; 2:cmd_path
  controller:
    wav_count_one_cmder: 5  # 一条命令词的语料数量
    play_mode: 1  # 1: 单条命令词所有语料读完循环；2：单条命令词单条语音读完循环；3：所有命令词所有语料读完循环；
    repeat_play_count: 1  # 一条语料的播放次数
    play_separator: 1.5  # 每次播放的时间间隔，单位: 秒
  log:
    log_filter:  # 日志的过滤关键字，出现在以下列表中关键字的日志，均不会被采集
      - agc handler
  interval: # 配置取值区间，用于识别计数，当无上限时，配置为 “x-max”; 当无下限时，配置为“min-x”（x表示数字）
    confidence:  # 置信度范围配置
      - 0-30
      - 30-max
    likelihood:  # likelihood范围配置
      - 0-0.35
      - 0.35-max
    svm:  # svm范围配置
      - 0-10
      - 10-max
  mapping:  # 串口和版本的映射关系,serial和version两个数组一一对应
    product: matong  # 产品名称
    serial:  # 串口号
      - COM15
      - COM14
    version:  # 项目名_版本号
      - matong_191225
      - matong_200120